version: "3"

services:
  sweets_db:
    image: "postgres"
    container_name: "sweets_db"
    restart: always
    environment:
      - POSTGRES_USER=secretdbuser
      - POSTGRES_PASSWORD=secretdbpass
      - POSTGRES_DB=sweetscollection
    ports:
      - "5432:5432"
    # volumes:
      # - ./postgres-data:/var/lib/postgresql/data
  
  sweets_api:
    build: .
    container_name: "sweets_api"
    restart: always
    environment:
      - DB_HOST=sweets_db
      - DB_PORT=5432
      - DB_USER=secretdbuser
      - DB_PASS=secretdbpass
    ports:
      - "9988:9988"