version: "3"

services:
  sweets_db:
    image: "postgres"
    container_name: "my_postgres"
    restart: always
    environment:
      - POSTGRES_USER=secretdbuser
      - POSTGRES_PASSWORD=secretdbpass
      - POSTGRES_DB=sweetscollection
    ports:
      - "5432:5432"
    # volumes:
      # - ./postgres-data:/var/lib/postgresql/data